# Generated by Django 4.1.13 on 2024-04-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdata',
            fields=[
                ('customer_id', models.IntegerField(default=123, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phno', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customerrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_preference', models.CharField(max_length=50)),
                ('Part_Name', models.CharField(max_length=50)),
                ('blank_name', models.CharField(max_length=50)),
                ('draft', models.CharField(max_length=60)),
                ('cname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('cpno', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('pr', models.CharField(max_length=50)),
                ('av', models.IntegerField(default=123)),
                ('qs', models.DateField()),
                ('tv', models.IntegerField()),
                ('sop', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customerdata')),
            ],
        ),
    ]
