# Generated by Django 4.1.13 on 2024-10-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdata',
            fields=[
                ('customer_id', models.IntegerField(default=123, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phno', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customerrequirements',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meal_preference', models.CharField(max_length=50)),
                ('Part_Name', models.CharField(max_length=50)),
                ('blank_name', models.CharField(max_length=50)),
                ('upload_file', models.FileField(max_length=250, upload_to='uploads/')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('cname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('cpno', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('pr', models.CharField(max_length=50)),
                ('av', models.IntegerField(default=123)),
                ('qs', models.DateField()),
                ('tv', models.IntegerField()),
                ('sop', models.DateField()),
                ('status', models.CharField(choices=[('working', 'Working'), ('pending', 'Pending'), ('completed', 'Completed')], default='working', max_length=20)),
                ('working_status', models.CharField(choices=[('working', 'Working'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_approved', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customerdata')),
            ],
        ),
    ]
