# Generated by Django 4.1.13 on 2024-06-25 04:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerrequirements',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_approved', max_length=20),
        ),
        migrations.AddField(
            model_name='customerrequirements',
            name='working_status',
            field=models.CharField(choices=[('working', 'Working'), ('pending', 'Pending'), ('completed', 'Completed')], default='working', max_length=20),
        ),
        migrations.CreateModel(
            name='FinalRequirement',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meal_preference', models.CharField(max_length=50)),
                ('Part_Name', models.CharField(max_length=50)),
                ('blank_name', models.CharField(max_length=50)),
                ('upload_file', models.FileField(max_length=250, upload_to='final_uploads/')),
                ('cname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('cpno', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('pr', models.CharField(max_length=50)),
                ('av', models.IntegerField(default=123)),
                ('qs', models.DateField()),
                ('tv', models.IntegerField()),
                ('sop', models.DateField()),
                ('working_status', models.CharField(choices=[('working', 'Working'), ('pending', 'Pending'), ('completed', 'Completed')], default='working', max_length=20)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], default='approved', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customerdata')),
            ],
        ),
    ]
