# Generated by Django 4.2.1 on 2024-01-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerrequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=50)),
                ('meal_preference', models.CharField(max_length=50)),
                ('Part_Name', models.CharField(max_length=50)),
                ('blank_name', models.CharField(max_length=50)),
                ('draft', models.CharField(max_length=60)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customerdata')),
            ],
        ),
    ]
