# Generated by Django 4.2.1 on 2024-01-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequirements',
            name='phone_no',
        ),
    ]
