# Generated by Django 4.1.13 on 2024-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequirements',
            name='upload_file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='uploads/'),
        ),
    ]
