# Generated by Django 4.1.13 on 2024-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_customerdata_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
