# Generated by Django 4.2.1 on 2024-01-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_customerrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequirements',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerrequirements',
            name='phone_no',
            field=models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
