# Generated by Django 4.1.13 on 2024-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customerdata_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequirements',
            name='working_status',
            field=models.CharField(choices=[('working', 'Working'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
